version: "3"

networks:
  private_network:

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - private_network

  admin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      - private_network

volumes:
  postgres-data:
